drop table ygo_card;
drop table users;
drop table user_deck;
select * from ygo_card;
select * from users;
select * from user_deck;

delete from ygo_card where id = 1;
insert into ygo_card values (default, '4-Starred Ladybug of Domm', 'Insect', 'Effect');

insert into user_deck select * from ygo_card where id = 1;

-- Create table for Monster Cards
create table ygo_card(
	id serial primary key,
	card_name VARCHAR not null,
	card_race VARCHAR not null,
	card_type VARCHAR not null
);

-- Create table for Users
create table users(
	id serial primary key,
	username VARCHAR unique not null,
	password VARCHAR not null,
	admin BOOLEAN not null
);

drop table SetoKaiba;

create table SetoKaiba(
	id serial,
	deck_name VARCHAR unique not null
);

create table ThePharaoh(
	id serial,
	deck_name VARCHAR unique not null
);

create table KaibaCorp(
	id serial,
	deck_name VARCHAR unique not null
);

create table Yuki(
	id serial,
	deck_name VARCHAR unique not null
);

create table user_deck(
	id serial,
	card_name VARCHAR not null,
	card_race VARCHAR not null,
	card_type VARCHAR not null
);

insert into users values
(default, 'SetoKaiba', 'NumberOne', true),
(default, 'ThePharaoh', 'thekingofgames', false),
(default, 'KaibaCorp', 'Mokuba', true),
(default, 'Yuki', 'gf', false);

insert into ygo_card values 
(default, '4-Starred Ladybug of Doom', 'Insect', 'Effect'), 
(default, 'Adamancipator Crystal', 'Rock', 'Effect'),
(default, 'Aeropixtree', 'Fairy', 'Effect'),
(default, 'Ahrima, The Wicked Warden', 'Fiend', 'Effect'),
(default, 'Aleirtt, the Ogdoadic Dark', 'Reptile', 'Effect'),
(default, 'Alien Stealthbuster', 'Reptile', 'Effect'),
(default, 'Altergeist Kunquery', 'Spellcaster', 'Effect'),
(default, 'Altitude Knight', 'Warrior', 'Effect'),
(default, 'Amano-Iwato', 'Rock', 'Effect'),
(default, 'Amanokujaki', 'Fiend', 'Effect'),
(default, 'Amazement Ambassador Bufo', 'Beast', 'Effect'),
(default, 'Amazement Attendant Comica', 'Machine', 'Effect'),
(default, 'Amunessia, the Ogdoadic Queen', 'Reptile', 'Effect'),
(default, 'Ancient Gear Frame', 'Machine', 'Effect'),
(default, 'Ancient Gear Gadget', 'Machine', 'Effect'),
(default, 'Ancient Gear Hydra', 'Machine', 'Effect'),
(default, 'Ancient Gear Wyvern', 'Machine', 'Effect'),
(default, 'Ancient Warriors - Deceptive Jia Wen', 'Beast-Warrior', 'Effect'),
(default, 'Ancient Warriors - Rebellious Lu Feng', 'Beast-Warrior', 'Effect'),
(default, 'Aria the Melodious Diva', 'Fairy', 'Effect'),
(default, 'Armed Dragon LV5', 'Dragon', 'Effect'),
(default, 'Armed Dragon LV7', 'Dragon', 'Effect'),
(default, 'Armed Dragon Thunder LV3', 'Dragon', 'Effect'),
(default, 'Armed Dragon Thunder LV5', 'Dragon', 'Effect'),
(default, 'Armed Dragon Thunder LV7', 'Dragon', 'Effect'),
(default, 'Armored Zombie', 'Zombie', 'Effect'),
(default, 'Aromage Laurel', 'Plant', 'Effect'),
(default, 'Aromage Marjoram', 'Plant', 'Effect'),
(default, 'Arsenal Summoner', 'Spellcaster', 'Effect'),
(default, 'Artifact Chakram', 'Fairy', 'Effect'), 
(default, 'Artifact Mjollnir', 'Fairy', 'Effect'),
(default, 'Artifact Vajra', 'Fairy', 'Effect'),
(default, 'Assault Beast', 'Beast-Warrior', 'Effect'),
(default, 'Astra Ghouls', 'Zombie', 'Effect'),
(default, 'Atlantean Dragoons', 'Sea Serpent', 'Effect'),
(default, 'Aussa the Earth Charmer', 'Spellcaster', 'Effect'),
(default, 'Awakening of the Possessed - Greater Inari Fire', 'Pyro', 'Effect'),
(default, 'Awakening of the Possessed - Nefariouser Archfiend', 'Beast', 'Effect'),
(default, 'Baby Mudragon', 'Dragon', 'Effect'),
(default, 'Background Dragon', 'Dragon', 'Effect'),
(default, 'Backup Operator', 'Cyberse', 'Effect'),
(default, 'Backup Secretary', 'Cyberse', 'Effect'),
(default, 'Bahalutiya, the Grand Radiance', 'Dragon', 'Effect'),
(default, 'Baobaboon', 'Plant', 'Effect'),
(default, 'Barrier Statue of the Inferno', 'Pyro', 'Effect'),
(default, 'Barrier Statue of the Stormwinds', 'Winged-Beast', 'Effect'),
(default, 'Basilius, Familiar of the Evil Eye', 'Fiend', 'Effect'),
(default, 'Batteryman Solar', 'Thunder', 'Effect'),
(default, 'Battlin'' Boxer Rib Gardna', 'Warrior', 'Effect'),
(default, 'Bayonater, the Baneful Barrel', 'Zombie', 'Effect'),
(default, 'Beast King Barbaros', 'Beast-Warrior', 'Effect'),
(default, 'Beatraptor', 'Dinosaur', 'Effect'),
(default, 'Beta the Magnet Warrior', 'Rock', 'Normal'),
(default, 'Blackeyes, the Plunder Patroll Seaguide', 'Fiend', 'Effect'),
(default, 'Blackland Fire Dragon', 'Dragon', 'Normal'),
(default, 'Blackwing -Decay the Ill Wind', 'Winged-Beast', 'Effect'),
(default, 'Blackwing - Harmattan the Dust', 'Winged-Beast', 'Effect'),
(default, 'Blue-Eyes Toon Dragon', 'Dragon', 'Effect'),
(default, 'Bluebeard, the Plunder Patroll Shipwright', 'Fiend', 'Effect'),
(default, 'Boot-Up Admirmal - Destroyer Dynamo', 'Machine', 'Effect'),
(default, 'Boot-Up Corporal - Command Dynamo', 'Machine', 'Effect'), 
(default, 'Breaker the Dark Magical Warrior', 'Spellcaster', 'Effect'),
(default, 'Breaker the Magical Warrior', 'Spellcaster', 'Effect'),
(default, 'Brinegir', 'Sea Serpent', 'Effect'),
(default, 'Brotherhood of the Fire Fist - Coyote', 'Beast-Warrior', 'Effect'),
(default, 'Bujin Mahitotsu', 'Beast-Warrior', 'Effect'),
(default, 'Bujin Torifune', 'Beast-Warrior', 'Effect'),
(default, 'Buster Blader', 'Warrior', 'Effect'),
(default, 'Buster Whelp of the Destruction Swordsman', 'Dragon', 'Effect'),
(default, 'Buzzsaw Shark', 'Fish', 'Effect'),
(default, 'Caligo Claw Crow', 'Winged-Beast', 'Effect'),
(default, 'Cannon Soldier', 'Machine', 'Effect'),
(default, 'Capacitor Stalker', 'Cyberse', 'Effect'),
(default, 'Capricious Darklord', 'Fairy', 'Effect'),
(default, 'Card Guard', 'Fiend', 'Effect'),
(default, 'Carpiponica, Mystical Beast of the Forest', 'Beast', 'Effect'),
(default, 'Cataclysmic Circumpolar Chilblainia', 'Fairy', 'Effect'),
(default, 'Cataclysmic Cryonic Coldo', 'Fairy', 'Effect'),
(default, 'Catapult Turtle', 'Aqua', 'Effect'),
(default, 'Catche Eve L2', 'Cyberse', 'Effect'),
(default, 'Celestia, Lightsworn Angel', 'Fairy', 'Effect'),
(default, 'Chaos Command Magician', 'Spellcaster', 'Effect'),
(default, 'Chaos Core', 'Fiend', 'Effect'),
(default, 'Chaos Emperor Dragon - Envoy of the End', 'Dragon', 'Effect'),
(default, 'Chaos Hunter', 'Fiend', 'Effect'),
(default, 'Choas Summoning Beast', 'Fiend', 'Effect'),
(default, 'Chobham Armor Dragon', 'Dragon', 'Effect'),
(default, 'Chronomaly Acambaro Figures', 'Rock', 'Effect'),
(default, 'Cipher Twin Raptor', 'Machine', 'Effect'),
(default, 'Cir, Malebranche of the Burning Abyss', 'Fiend', 'Effect'), 
(default, 'Clavkiys, the Magikey Skyblaster', 'Warrior', 'Effect'),
(default, 'Clock Wyvern', 'Cyberse', 'Effect'),
(default, 'Constellar Caduceus', 'Spellcaster', 'Effect'),
(default, 'Contact "C"', 'Insect', 'Effect'),
(default, 'Converging Wills Dragon', 'Dragon', 'Effect'),
(default, 'Crimson Resonator', 'Fiend', 'Effect'),
(default, 'Crowley, the Magistus of Grimoires', 'Spellcaster', 'Effect'),
(default, 'Crowned by the World Chalice', 'Spellcaster', 'Effect'),
(default, 'Crusadia Reclusia', 'Spellcaster', 'Effect'),
(default, 'Crystal Beast Amber Mammoth', 'Beast', 'Effect'),
(default, 'Crystal Beast Sapphire Pegasus', 'Beast', 'Effect'),
(default, 'Crystal Girl', 'Spellcaster', 'Effect'),
(default, 'Crystron Prasiortle', 'Machine', 'Effect'),
(default, 'Crystron Smiger', 'Machine', 'Effect'),
(default, 'Cuben', 'Thunder', 'Effect'),
(default, 'Cupid Dunk', 'Fairy', 'Effect'),
(default, 'Curse of Dragon, the Cursed Dragon', 'Dragon', 'Effect'),
(default, 'Cyber Dragon', 'Machine', 'Effect'),
(default, 'Cyber Dragon Core', 'Machine', 'Effect'),
(default, 'Cyber Eltanin', 'Machine', 'Effect'),
(default, 'Cyber-Stein', 'Machine', 'Effect'),
(default, 'Cyberdark Cannon', 'Dragon', 'Effect'),
(default, 'Cyberdark Edge', 'Machine', 'Normal'),
(default, 'Cyberdark Horn', 'Machine', 'Effect'),
(default, 'Cyberdark Keel', 'Machine', 'Normal'),
(default, 'Cyberse Gadget', 'Cyberse', 'Effect'),
(default, '"A" Cell Recombination Device', 'Magic Card', 'Quick Play'),
(default, 'A.I. Contact', 'Magic Card', 'Normal Spell'),
(default, 'A.I. Challenge You', 'Trap Card', 'Continuous Trap'),
(default, 'A.I. Meet You', 'Magic Card', 'Normal Spell'),
(default, 'A.I.Q', 'Trap Card', 'Continuous Trap'),
(default, 'A Deal with Dark Ruler', 'Magic Card', 'Quick Play'),
(default, 'A Wind Monster Appears', 'Magic Card', 'Normal Spell'),
(default, 'Adominable Chamber of the Unchained', 'Trap Card', 'Normal Trap'),
(default, 'Abomination'' Prison', 'Magic Card', 'Normal Spell'),
(default, 'Action Magic - Double Banking', 'Magic Card', 'Quick Play'),
(default, 'Action Magic - Full Turn', 'Magic Card', 'Quick Play'),
(default, 'Air Cracking Storm', 'Magic Card', 'Equip Card'),
(default, 'Altergeist Manifestation', 'Trap Card', 'Normal Trap'),
(default, 'Amaze Attraction Horror House', 'Trap Card', 'Normal Trap'),
(default, 'Amaze Attraction Majestic Merry-Go-Round', 'Trap Card', 'Normal Trap'),
(default, 'Amaze Attraction Rapid Racing', 'Trap Card', 'Normal Trap'),
(default, 'Amaze Attraction Wonder Wheel', 'Trap Card', 'Normal Trap'),
(default, 'Amaze Attraction Viking Vortex', 'Trap Card', 'Normal Trap'),
(default, 'Amazement Precious Park', 'Magic Card', 'Quick Play'),
(default, 'Amazement Special Show', 'Magic Card', 'Quick Play'),
(default, 'Amazoness Onslaught', 'Trap Card', 'Continuous Trap'),
(default, 'Amorphous Persona', 'Magic Card', 'Equip Card'),
(default, 'Amplifier', 'Magic Card', 'Equip Card'),
(default, 'Ancient City- Rainbow Ruins', 'Magic Card', 'Field Card'),
(default, 'Ancient Warriors Saga - Borrowing of Arrows', 'Magic Card', 'Continuous Spell'),
(default, 'Ancient Warriors Saga - Chivalrous Path', 'Trap Card', 'Continuous Trap'),
(default, 'Ancient Warriors Saga - East-by-South Winds', 'Magic Card', 'Continuous Spell'),
(default, 'Anti-Spell Fragrance', 'Trap Card', 'Continuous Trap'),
(default, 'Archfiend''s Oath', 'Magic Card', 'Continuous Spell'),
(default, 'Archiend''s Roar', 'Trap Card', 'Normal Trap'),
(default, 'Archfiend''s Staff of Despair', 'Magic Card', 'Equip Card'),
(default, 'Armed Dragon Blitz', 'Magic Card', 'Normal Spell'),
(default, 'Armed Dragon Flash', 'Magic Card', 'Quick Play'),
(default, 'Armed Dragon Lightning', 'Magic Card', 'Continuous Spell'),
(default, 'Armed Dragon Thunderbolt', 'Trap Card', 'Normal Trap'),
(default, 'Armed Dragon Ritual', 'Magic Card', 'Ritual Spell'),
(default, 'Armored Glass', 'Trap Card', 'Normal Trap'),
(default, 'Armory Call', 'Trap Card', 'Normal Trap'),
(default, 'Aroma Gardening', 'Magic Card', 'Continuous Spell'),
(default, 'Ascending Soul', 'Magic Card', 'Continuous Spell'),
(default, 'Awakening of the Possessed', 'Magic Card', 'Continuous Spell'),
(default, 'Awakening of the Sacred Beasts', 'Trap Card', 'Continuous Trap'),
(default, 'Ayers Rock Sunrise', 'Magic Card', 'Normal Spell'),
(default, 'Backup Squad', 'Magic Card', 'Continuous Spell'),
(default, 'Bad Luck Blast', 'Trap Card', 'Normal Trap'),
(default, 'Basal Rose Shoot', 'Magic Card', 'Quick Play'),
(default, 'Battleguard Howling', 'Trap Card', 'Normal Trap'),
(default, 'Battleguard Rage', 'Trap Card', 'Continuous Trap'),
(default, 'Beacon of White', 'Magic Card', 'Equip Card'),
(default, 'Beast King Unleashed', 'Trap Card', 'Continuous Trap'),
(default, 'Beast Magic Attack', 'Magic Card', 'Quick Play'),
(default, 'Beetrooper Formation', 'Magic Card', 'Field Card'),
(default, 'Beetrooper Fly & Sting', 'Trap Card', 'Counter Trap'),
(default, 'Birth of the Prominence Flame', 'Magic Card', 'Normal Spell'),
(default, 'Blast Held by a Tribute', 'Trap Card', 'Normal Trap'),
(default, 'Black Illusion Ritual', 'Magic Card', 'Ritual Spell'),
(default, 'Blaze Cannon', 'Magic Card', 'Quick Play'),
(default, 'Blizzard', 'Magic Card', 'Quick Play'),
(default, 'Block Attack', 'Magic Card', 'Normal Spell'),
(default, 'Boo-Boo Game', 'Trap Card', 'Normal Trap'),
(default, 'Book of Eclipse', 'Magic Card', 'Quick Play'),
(default, 'Book of Moon', 'Magic Card', 'Quick Play'),
(default, 'The Book of the Law', 'Magic Card', 'Quick Play'),
(default, 'Boompoline!!', 'Trap Card', 'Continuous Trap'),
(default, 'Boon of the Meklord Emperor', 'Magic Card', 'Normal Spell'),
(default, 'Boot-Up Order - Gear Charge', 'Magic Card', 'Continuous Spell'),
(default, 'Born from Draconis', 'Trap Card', 'Normal Trap'),
(default, 'Bottomless Trap Hole', 'Trap Card', 'Normal Trap'),
(default, 'Bound Wand', 'Magic Card', 'Equip Card'),
(default, 'Brain Control', 'Magic Card', 'Normal Spell'),
(default, 'Brainwashing Beam', 'Trap Card', 'Continuous Trap'),
(default, 'Branded Bound', 'Magic Card', 'Normal Spell'),
(default, 'Breath of Acclamation', 'Magic Card', 'Ritual Spell'),
(default, 'Breaking of the World', 'Magic Card', 'Field Card'),
(default, 'Brutual Beast Battle', 'Trap Card', 'Normal Trap'),
(default, 'Bug Emergency', 'Trap Card', 'Normal Trap'),
(default, 'Bug Matrix', 'Magic Card', 'Field Card'),
(default, 'Bug Signal', 'Magic Card', 'Quick Play'),
(default, 'Bujincandescence', 'Magic Card', 'Continuous Spell'),
(default, 'Burning Soul', 'Magic Card', 'Quick Play'),
(default, 'Bye Bye Damage', 'Trap Card', 'Normal Trap'),
(default, 'Call of the Archfiend', 'Trap Card', 'Continuous Trap'),
(default, 'Called by the Grave', 'Magic Card', 'Quick Play'),
(default, 'Card Advance', 'Magic Card', 'Normal Spell'),
(default, 'Card Destruction', 'Magic Card', 'Normal Spell'),
(default, 'Cattle Call', 'Magic Card', 'Quick Play'),
(default, 'Cauldron of the Old Man', 'Magic Card', 'Continuous Spell'),
(default, 'Cerculean Skyfire', 'Magic Card', 'Continuous Spell'),
(default, 'Chaos Infinity', 'Trap Card', 'Normal Trap'),
(default, 'Chaos Seed', 'Magic Card', 'Normal Spell'),
(default, 'Chronomaly Esperanza Glyph', 'Trap Card', 'Normal Trap'),
(default, 'Chronomaly Temple - Trilithon', 'Magic Card', 'Continuous Spell'),
(default, 'Circle of the Fire Kings', 'Magic Card', 'Quick Play'),
(default, 'Cloudian Aerosol', 'Magic Card', 'Normal Spell'),
(default, 'Column Switch', 'Magic Card', 'Quick Play'),
(default, 'Contact Gate', 'Magic Card', 'Normal Spell'),
(default, 'Contract with the Dark Master', 'Magic Card', 'Ritual Spell'),
(default, 'Converging Wishes', 'Trap Card', 'Normal Trap'),
(default, 'Corrosive Scale', 'Trap Card', 'Normal Trap'),
(default, 'Cosmic Cyclone', 'Magic Card', 'Quick Play'),
(default, 'Cosmos Channeling', 'Magic Card', 'Continuous Spell'),
(default, 'Counter Gem', 'Trap Card', 'Normal Trap'),
(default, 'Cross-Dimensional Duel', 'Trap Card', 'Normal Trap'),
(default, 'Court of Cards', 'Trap Card', 'Continuous Trap'),
(default, 'Crackdown', 'Trap Card', 'Continuous Trap'),
(default, 'Cross Breed', 'Magic Card', 'Normal Spell'),
(default, 'Cross Over', 'Magic Card', 'Normal Spell'),
(default, 'Crystal Abundance', 'Magic Card', 'Normal Spell'),
(default, 'Crystal Beacon', 'Magic Card', 'Normal Spell'),
(default, 'Crystal Blessing', 'Magic Card', 'Normal Spell'),
(default, 'Crystal Conclave', 'Trap Card', 'Continuous Trap'),
(default, 'Crystal Release', 'Magic Card', 'Equip Card'),
(default, 'Crystal Tree', 'Magic Card', 'Continuous Spell'),
(default, 'Curse of the Shadow Prison', 'Magic Card', 'Field Card'),
(default, 'Cyber Emergency', 'Magic Card', 'Normal Spell'),
(default, 'Cyber Energy Shock', 'Magic Card', 'Quick Play'),
(default, 'Cyberse Beacon', 'Trap Card', 'Normal Trap'),
(default, 'Cynet Conflict', 'Trap Card', 'Counter Trap'),
(default, 'Cynet Optimization', 'Magic Card', 'Continuous Spell'),
(default, 'Cynet Regression', 'Trap Card', 'Normal Trap');